version: '3.8'

services:
  db_sleakops:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api_sleakops:
    build: .
    deploy:
      replicas: 2
    depends_on:
      - db_sleakops
    environment:
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_IP}:5432/${DATABASE_NAME}
    expose:
      - "8000"
    volumes:
      - ./app:/app
      - .env:/app/.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  nginx:
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api_sleakops

volumes:
  postgres_data:
